version: '3.1'

services:

  db:
    image: mysql:8
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./schema:/docker-entrypoint-initdb.d/
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
#    command:
#      - /bin/bash
#      - -c
#      - |
#      - mysql -u app -p pass app -e "show tables" |
#        grep -v Tables_in |
#        grep -v "+" |
#        gawk '{print "TRUNCATE TABLE `" $1 "`;"}' |
#        mysql -u app -p pass app"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080